#!/bin/bash

cd /home/ec2-user/app

# Fix ownership & permissions
sudo chown -R ec2-user:ec2-user /home/ec2-user/app
sudo chmod -R 755 /home/ec2-user/app

# Install dependencies
npm install

# Stop any running process
/usr/bin/pm2 stop all || true

# Start the server with PM2
/usr/bin/pm2 start server.js
